package errors
 
var (
    StatusBadRequest                   = NewError(400, "StatusBadRequest")
    StatusUnauthorized                 = NewError(401, "StatusUnauthorized")
    StatusPaymentRequired              = NewError(402, "StatusPaymentRequired")
    StatusForbidden                    = NewError(403, "StatusForbidden")
    StatusNotFound                     = NewError(404, "StatusNotFound")
    StatusMethodNotAllowed             = NewError(405, "StatusMethodNotAllowed")
    StatusNotAcceptable                = NewError(406, "StatusNotAcceptable")
    StatusProxyAuthRequired            = NewError(407, "StatusProxyAuthRequired")
    StatusRequestTimeout               = NewError(408, "StatusRequestTimeout")
    StatusConflict                     = NewError(409, "StatusConflict")
    StatusGone                         = NewError(410, "StatusGone")
    StatusLengthRequired               = NewError(411, "StatusLengthRequired")
    StatusPreconditionFailed           = NewError(412, "StatusPreconditionFailed")
    StatusRequestEntityTooLarge        = NewError(413, "StatusRequestEntityTooLarge")
    StatusRequestURITooLong            = NewError(414, "StatusRequestURITooLong")
    StatusUnsupportedMediaType         = NewError(415, "StatusUnsupportedMediaType")
    StatusRequestedRangeNotSatisfiable = NewError(416, "StatusRequestedRangeNotSatisfiable")
    StatusExpectationFailed            = NewError(417, "StatusExpectationFailed")
    StatusTeapot                       = NewError(418, "StatusTeapot")
    StatusMisdirectedRequest           = NewError(421, "StatusMisdirectedRequest")
    StatusUnprocessableEntity          = NewError(422, "StatusUnprocessableEntity")
    StatusLocked                       = NewError(423, "StatusLocked")
    StatusFailedDependency             = NewError(424, "StatusFailedDependency")
    StatusTooEarly                     = NewError(425, "StatusTooEarly")
    StatusUpgradeRequired              = NewError(426, "StatusUpgradeRequired")
    StatusPreconditionRequired         = NewError(428, "StatusPreconditionRequired")
    StatusTooManyRequests              = NewError(429, "StatusTooManyRequests")
    StatusRequestHeaderFieldsTooLarge  = NewError(431, "StatusRequestHeaderFieldsTooLarge")
    StatusUnavailableForLegalReasons   = NewError(451, "StatusUnavailableForLegalReasons")
 
    StatusInternalServerError           = NewError(500, "StatusInternalServerError")
    StatusNotImplemented                = NewError(501, "StatusNotImplemented")
    StatusBadGateway                    = NewError(502, "StatusBadGateway")
    StatusServiceUnavailable            = NewError(503, "StatusServiceUnavailable")
    StatusGatewayTimeout                = NewError(504, "StatusGatewayTimeout")
    StatusHTTPVersionNotSupported       = NewError(505, "StatusHTTPVersionNotSupported")
    StatusVariantAlsoNegotiates         = NewError(506, "StatusVariantAlsoNegotiates")
    StatusInsufficientStorage           = NewError(507, "StatusInsufficientStorage")
    StatusLoopDetected                  = NewError(508, "StatusLoopDetected")
    StatusNotExtended                   = NewError(510, "StatusNotExtended")
    StatusNetworkAuthenticationRequired = NewError(511, "StatusNetworkAuthenticationRequired")
)